config/routes.rb
Rails.application.routes.draw do

  resources :products
  devise_for :normal_users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  resources :encomendas

  match "carts/add/:id" => "carts#add", as: :add_to_carts, via: :get
  match "carts/clear" => "carts#clear", via: :get
  resources :carts

  root 'main#index'
  match "produto/:id" => "main#show", as: :main_produto, via: :get
  match "search" => "main#search", as: :search, via: :get
  match "search_results" => "main#search_results", as: :search_results, via: :post
  match "categoria/:categoria" => "main#categoria", as: :categoria, via: :get

end

app/controllers/main_controller.rb
class MainController < ApplicationController

    
  def index
  	@products = Product.order(:name)
    @categorias = Category.order(:name)
  end

  def show
  	@product = Product.find(params[:id])
  end

  def search 

  end 

  def search_results
    #@products = Product.where(:name => params[:keywords])
    @products = Product.where("name LIKE ?", "%#{params[:keywords]}%")
  end
    def categoria
    @products = Product.where(:category_id => params[:categoria])
  end

end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/categoria.html.erb
<h2>Produtos da Categoria</h2>

<% if @products.empty? %>
	<p>Não foi encontrado nenhum produto dessa Categoria </p>
	<!--seguranca CSS(se colocar raw antes dos params)  <script> alert("A");</script>   -->
	<%end%>
  <div class="row">
    <% @products.each do |p| %>
      <div class="col-sm-3 text-center">
        <div class="panel panel-default">
            <div class="panel-body">
              <p> 
              <p><h4><%= p.name %></h4></p>
              <a href="#" class="thumbnail">
              <%= image_tag p.image %>
              </a>
              <p> <%= p.description %></p> 
              <p> R<%= number_to_currency(p.price) %> </p>
              <a href="#" class="btn btn-danger"> Comprar</a>
              <%= link_to  "Detalhes", main_produto_path( p), :class => 'btn btn-primary' %> 
              </p>
            </div>
        </div>
     </div>
    <% end %>
  </div>

  <%= link_to  "Voltar", root_path, :class => 'btn btn-success' %> 

app/views/main/index.html.erb
<!DOCTYPE html>


<!--
	<div class="container">
<div class="jumbotron text-center">
<h2>Promocoes</h2>
<p>Compre e ganhe 20% de desconto</p>
</div>
-->
      <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval = "3000">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
       
        <!-- Wrapper for slides -->
        <div class="carousel-inner">
          <div class="item active">
            <img src= "<%= asset_path('smartphones.png') %>" alt="..." class ="img-responsive">
            <div class="carousel-caption">
                <h3>Promoções</h3>
            </div>
          </div>
          <div class="item">
            <img src="<%= asset_path('smartphones.png') %>" alt="...">
       <     <div class="carousel-caption">
                <h3>Promoções</h3>
            </div>
          </div>
          <div class="item">
            <img src="<%= asset_path('smartphones.png') %>" alt="...">
            <div class="carousel-caption">
                <h3>Promoções</h3>
            </div>
          </div>
        </div>
       
        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      </div> <!-- Carousel -->

    <div class="conteudo">

  <div class="row">

  <div class ="col-sm-2">
<div class="panel panel-default pull-left text-center">
  <!-- Default panel contents -->
  <div class="panel-heading"><h3> Categorias</h3></div>
  <ul class="list-group">
          <% @categorias.each do |c| %>
             <li class="list-group-item"><h4> <%= link_to c.name, categoria_path(c) %> </h4></li>
          <% end %>
  </ul>
</div>
</div>

        <div class="col-sm-10 text-center">
    <% @products.each do |p| %>
      <div class="col-sm-4 text-center">
        <div class="panel panel-default">
            <div class="panel-body">
              <p>
              <p><h4><%= p.name %></h4></p>
            <!--  <a href="#" class="thumbnail"> -->
                  <a class="thumbnail" width = "100%">
              <%= image_tag p.image %>
              </a>
              <p> <%= p.description %></p> 
              <p> R<%= number_to_currency(p.price) %> </p>
          <!--    <%#= link_to  "Comprar", new_encomenda_path, :class => 'btn btn-danger' %> -->
           <!--   <a  <  class="btn btn-primary"> Detalhes </a>  -->
               <%= link_to  "Carrinho", :controller => 'carts', :action => 'add', :id => p %>

              <%= link_to  "Detalhes", main_produto_path(p),  :class => 'btn btn-primary' %> 
              </p>
            </div>
        </div>
     </div>
    <% end %>
  </div>


</div>


 <!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<div class="modal fade" id="login" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4>Login<h4>
      </div>
      <div class="modal-body">
        
<div class="input-group">
  <span class="input-group-addon"</span>
  <input type="text" class="form-control" placeholder="Username">
</div>

<div class="input-group">
  <span class="input-group-addon"</span>
  <input type="text" class="form-control" placeholder="Senha">
</div>

      <a href="#" class="btn btn-danger"> Login</a>
      <a href="#" class="btn btn-danger"> Logout</a>
      <a href="usuarios/new" class="btn btn-danger"> Cadastrar Usuario</a>

      </div>
      <div class="modal-footer">
        <a class="btn btn-primary" data-dismiss="modal">Close</a>
      </div>
    </div>
  </div>
</div>



 <!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<div class="modal fade" id="produto" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4>Nome<h4>
      </div>
      <div class="modal-body">
        
      </div>
      <div class="modal-footer">
        <a class="btn btn-primary" data-dismiss="modal">Close</a>
      </div>
    </div>
  </div>
</div>

app/views/main/search.html.erb
<h2>Buscar</h2>

	<%= form_tag search_results_path do %>

	<%= text_field_tag :keywords %>

	<%= submit_tag 'Search', :class => 'btn btn-primary' %>

	<% end %>

app/views/main/search_results.html.erb
<h2>Resultado da Busca</h2>

<% if @products.empty? %>
	<p>Não foi encontrado nenhum produto para '<%= params[:keywords] %>' </p>
	<!--seguranca CSS(se colocar raw antes dos params)  <script> alert("A");</script>   -->
	<%end%>
  <div class="row">
    <% @products.each do |p| %>
      <div class="col-sm-3 text-center">
        <div class="panel panel-default">
            <div class="panel-body">
              <p> 
              <p><h4><%= p.name %></h4></p>
              <a href="#" class="thumbnail">
              <%= image_tag p.image %>
              </a>
              <p> <%= p.description %></p> 
              <p> R<%= number_to_currency(p.price) %> </p>
              <a href="#" class="btn btn-danger"> Comprar</a>
              <%= link_to  "Detalhes", main_produto_path( p), :class => 'btn btn-primary' %> 
              </p>
            </div>
        </div>
     </div>
    <% end %>
  </div>

  <%= link_to  "Voltar", root_path, :class => 'btn btn-success' %> 

app/views/main/show.html.erb
  	    <div class="panel panel-default text-center">
            <div class="panel-body">
              <p>
              <p><h2><%= @product.name %></h2></p>

              <%= image_tag @product.image.url(:medium) %>

              <p><h4> Descrição: <%= @product.description %></h4></p> 

              <% if @product.category %>
              <p><h4> Categoria: <%= @product.category.name %></h4></p> 
              <% end %>

              <p><h4> Preço: R<%= number_to_currency( @product.price) %> </h4></p>
              <a href="#" class="btn btn-danger"> Comprar</a>
              <%= link_to  "Voltar", root_path, :class => 'btn btn-primary' %> 
              </p>
        </div>
      </div>