config/routes.rb
Rails.application.routes.draw do

  resources :products
  devise_for :normal_users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  resources :encomendas

  match "carts/add/:id" => "carts#add", as: :add_to_carts, via: :get
  match "carts/clear" => "carts#clear", via: :get
  resources :carts

  root 'main#index'
  match "produto/:id" => "main#show", as: :main_produto, via: :get
  match "search" => "main#search", as: :search, via: :get
  match "search_results" => "main#search_results", as: :search_results, via: :post
  match "categoria/:categoria" => "main#categoria", as: :categoria, via: :get

end

app/models/product.rb
class Product < ActiveRecord::Base

belongs_to :category

has_many :cart_items
has_many :carts, :through => :cart_items


has_attached_file :image, :styles => { :small  => "150x150>", :medium  => "300x300>"},
				  :url => "/assets/images/:id/:style/:basename.:extension",
				  :path => ":rails_root/public/assets/images/:id/:style/:basename.:extension"



#do_not_validate_attachment_file_type :image
validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
#validates_attachment_presence :image
#validates_attachment_size :image, :less_than => 5.megabytes
#validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']

validates :description, :name, :price, :presence=> true
validates :price, :numericality => true

end

#,
#				  :url => "/assets/images/:id/:style/:basename.:extension",
#				  :path => ":rails_root/public/assets/images/:id/:style/:basename.:extension"

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.order(:name)
  end

  # GET /products/1/edit
  def edit
    @categories = Category.order(:name)
  end

  # POST /products
  # POST /products.json

    def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end 

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :description, :image, :category_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product, :html => { :class => "form-horizontal product" } do |f| %>

  <% if @product.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
    <%=f.error_span(:price) %>
  </div>

  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>

  <div class="form-group">
    <%= f.label :category_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
            <%= f.collection_select :category_id, @categories, :id, :name, {class: "form-control"} %>
            <!--, {prompt: "Selecione uma Categoria"} -->
    </div> 
    <%=f.error_span(:category_id) %>
  </div>


  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.file_field :image, :class => 'btn btn-default' %>
      

      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/products/_product.html.erb
        <div class="panel panel-default">
            <div class="panel-body">
              <p>
              <p><h4><%= product.name %></h4></p>
              <a href="#" class="thumbnail">
              <%= image_tag product.image %>
              </a>
              <p> <%= product.description %></p> 
              <p> R<%= number_to_currency(product.price) %> </p>
              <a href="#" class="btn btn-danger"> Comprar</a>
           <!--   <a  <  class="btn btn-primary"> Detalhes </a>  -->
              <%= link_to  "Detalhes", main_produto_path(product), :class => 'btn btn-primary' %> 
              </p>
            </div>
        </div>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>

      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.id, product_path(product) %></td>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.description %></td>

        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_product_path(product), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      product_path(product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_product_path,
            :class => 'btn btn-primary' %>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @product.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @product.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @product.description %></dd>

    <% if @product.category %>
    <dt><strong><%= model_class.human_attribute_name(:category) %>:</strong></dt>
    <dd><%= @product.category.name %></dd>
    <%end%>

  <%= image_tag @product.image.url(:medium) %>


</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>