config/routes.rb
Rails.application.routes.draw do

  resources :products
  devise_for :normal_users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  resources :encomendas

  match "carts/add/:id" => "carts#add", as: :add_to_carts, via: :get
  match "carts/clear" => "carts#clear", via: :get
  resources :carts

  root 'main#index'
  match "produto/:id" => "main#show", as: :main_produto, via: :get
  match "search" => "main#search", as: :search, via: :get
  match "search_results" => "main#search_results", as: :search_results, via: :post
  match "categoria/:categoria" => "main#categoria", as: :categoria, via: :get

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LojaWeb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>



</head>
<body>



  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= value %>
      </div>
  <% end %>


<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand"> LojaAlexandre </a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">

         <li class="active"><%= link_to "Inicio", root_path %></li>

         <li><%= link_to "Cart", carts_path %><li>

         <li> <%= link_to "Busca", search_path %></li>
          <li><a href="#about" data-toggle="modal">Sobre</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categorias <b class="caret"></b></a>
            <ul class="dropdown-menu">
        <!--      <li class="dropdown-header">Produtos Eletronicos</li>
              <li><a href="#">Computadores</a></li>
              <li><a href="#">Tablets</a></li>
              <li class="divider"></li>
              <li class="dropdown-header">Produtos de casa</li>
              <li><a href="#">Geladeira</a></li>
              <li><a href="#">Fogao</a></li> -->
              <li class="dropdown-header">Categorias</li>
              <% @categoriesNav.each do |c| %>
              <li><a> <%= link_to c.name, categoria_path(c) %></a> </li>
              <% end %>

            </ul>
          </li>
        <li><a href="#contact" data-toggle="modal">Contato</a></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Area Usuario<b class="caret"></b></a>
            <ul class="dropdown-menu">

              <li class="dropdown-header">Admin</li>
        <li><%= link_to "Cadastro Produtos", products_path %></li>
        <li><%= link_to "Cadastro Categorias", categories_path %></li>
            </ul>

          </li>

          <% if normal_user_signed_in? %>
            Signed in as <%= current_normal_user.email %>.
            <%= link_to "Sign out", destroy_normal_user_session_path, :method => :delete %>
            <% else %>
            <%= link_to "Sign up", new_normal_user_registration_path %> or <%= link_to "sign in", new_normal_user_session_path %>
            <% end %>

      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>


<div class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
	<div class="container">
		<div class="navbar-text pull-left">
			<p>© 2014 Loja Alexandre.</p>
		</div>
		<div class="navbar-text pull-right">
			<a href="#"><i class="fa fa-facebook-square fa-2x"></i></a>
		</div>
	</div>
</div>













 <!-- Bootstrap core JavaScript
================================================== -->
<!-- Mensagens -->
<div class="modal fade" id="contact" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4>Contato<h4>
			</div>
			<div class="modal-body">
				<p>Mande um e-mail para alexandrekry@gmail.com</p>
			</div>
			<div class="modal-footer">
				<a class="btn btn-primary" data-dismiss="modal">Close</a>
			</div>
		</div>
	</div>
</div>


<div class="modal fade" id="about" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4>Sobre<h4>
      </div>
      <div class="modal-body">
        <p>Site criado para o projeto de Orientação a Objetos</p>
        <p>Unb FGA</p>
      </div>
      <div class="modal-footer">
        <a class="btn btn-primary" data-dismiss="modal">Close</a>
      </div>
    </div>
  </div>
</div>

     <% if notice %>
          <p id="notice"><%= notice %></p>
     <% end %>


  <div class="container">

 <!-- 
================================================== -->
<!-- Mensagens END-->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>


<%= yield %>
</div>

 <!-- 
================================================== -->
<!-- Mensagens END-->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

</body>
</html>