config/routes.rb
Rails.application.routes.draw do

  resources :products
  devise_for :normal_users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  resources :encomendas

  match "carts/add/:id" => "carts#add", as: :add_to_carts, via: :get
  match "carts/clear" => "carts#clear", via: :get
  resources :carts

  root 'main#index'
  match "produto/:id" => "main#show", as: :main_produto, via: :get
  match "search" => "main#search", as: :search, via: :get
  match "search_results" => "main#search_results", as: :search_results, via: :post
  match "categoria/:categoria" => "main#categoria", as: :categoria, via: :get

end

app/models/encomenda.rb
class Encomenda < ActiveRecord::Base
	  has_one :cart

end

app/controllers/encomendas_controller.rb
class EncomendasController < InheritedResources::Base

	before_filter :authenticate_normal_user!


  private

    def encomenda_params
      params.require(:encomenda).permit(:endereco, :cartao_credito, :comprador)
    end



end

app/helpers/encomendas_helper.rb
module EncomendasHelper
end

app/views/encomendas/_form.html.erb
<%= form_for(@encomenda) do |f| %>
  <% if @encomenda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@encomenda.errors.count, "error") %> prohibited this encomenda from being saved:</h2>

      <ul>
      <% @encomenda.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :endereco %><br>
    <%= f.text_field :endereco %>
  </div>
  <div class="field">
    <%= f.label :cartao_credito %><br> 
    <%= f.text_field :cartao_credito %>
  </div>
    
 <!--   <%#= current_normal_user.email :cliente %> -->

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/encomendas/edit.html.erb
<h1>Editing encomenda</h1>

<%= render 'form' %>

<%#= link_to 'Show', @encomenda %> |
<%= link_to "Back", carts_clear_path  %>

app/views/encomendas/index.html.erb
<h1>Listing encomendas</h1>

<table>
  <thead>
    <tr>
      <th>Endereco</th>
      <th>Cartao credito</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @encomendas.each do |encomenda| %>
      <tr>
        <td><%= encomenda.endereco %></td>
        <td><%= encomenda.cartao_credito %></td>
        <td><%= link_to 'Show', encomenda %></td>
        <td><%= link_to 'Edit', edit_encomenda_path(encomenda) %></td>
        <td><%= link_to 'Destroy', encomenda, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Encomenda', new_encomenda_path %>

app/views/encomendas/new.html.erb
<h1> Encomenda</h1>

<%= render 'form' %>

app/views/encomendas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Endereco:</strong>
  <%= @encomenda.endereco %>
</p>

<p>
  <strong>Cartao credito:</strong>
  <%= @encomenda.cartao_credito %>
</p>

<%= link_to 'Edit', edit_encomenda_path(@encomenda) %> |
<%= link_to 'Back', carts_clear_path  %>